# Site settings
name: SuperRunt
title: ""
email: superrunt@gmail.com
description: "Nerd stuff, code, code samples, angular, javascript, iOS, jquery"
baseurl: ""
url: "http://superrunt.com"

# Build settings
markdown: kramdown
permalinks: pretty

exclude: ['*.json', 'Gruntfile.js', 'config.rb', 'node_modules', 'sass', 'stylesheets', 'js', 'debug', 'production', 'vagrant']

# Format defaults
defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
  -
    scope:
      path: "stuff/"
      type: "post"
    values:
      layout: "post" # overrides previous default layout
#      author: "Me"
