# Site settings
name: SuperRunt
title: ""
email: superrunt@gmail.com
description: "Nerd stuff, code, code samples, angular, javascript, iOS, jquery"
baseurl: ""
url: "http://superrunt.com"

# Build settings
markdown: kramdown
permalinks: pretty

safe: true
lsi: false

exclude: ['*.json', 'Gruntfile.js', 'config.rb', 'node_modules', 'sass', 'stylesheets', 'js', 'debug', 'production', 'vagrant']

